//
// Game.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation
import RESTAPI

public struct Game: Codable {

    public var _id: UUID
    public var owner: User?
    public var ownerSide: Side?
    public var guest: User?
    public var steps: [Step]?
    public var status: GameStatus?
    
    public init(_id: UUID, owner: User?, ownerSide: Side?, guest: User?, steps: [Step]?, status: GameStatus?) { 
        self._id = _id
        self.owner = owner
        self.ownerSide = ownerSide
        self.guest = guest
        self.steps = steps
        self.status = status
    }
    
    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case owner
        case ownerSide
        case guest
        case steps
        case status
    }
}

extension Game: ValidJSONData { }

extension Game: JSONCodable { }

