//
// User.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation
import RESTAPI

public struct User: Codable {

    public var _id: UUID
    /** Unique identifier of the user */
    public var name: String
    
    public init(_id: UUID, name: String) { 
        self._id = _id
        self.name = name
    }
    
    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case name
    }
}

extension User: ValidJSONData { }

extension User: JSONCodable { }
