//
// GameStatus.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import RESTAPI

public enum GameStatus: String, Codable {
    case pending = "pending"
    case ongoing = "ongoing"
    case finished = "finished"
}

extension GameStatus: ValidJSONData { }

extension GameStatus: JSONCodable { }
