//
// Side.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import RESTAPI

public enum Side: String, Codable {
    case dark = "dark"
    case light = "light"
}

extension Side: ValidJSONData { }

extension Side: JSONCodable { }

extension Side: Equatable { }

prefix func !(_ rhs: Side) -> Side {
    switch rhs {
    case .dark: return .light
    case .light: return .dark
    }
}
