//
// Side.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import RESTAPI

public enum Side: String, Codable {
    case dark = "dark"
    case light = "light"
}

extension Side: ValidJSONData { }

extension Side: JSONCodable { }
