//
// Step.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation
import RESTAPI

public struct Step: Codable {

    public var position: Position?
    public var figure: Figure?
    
    public init(position: Position?, figure: Figure?) { 
        self.position = position
        self.figure = figure
    }
}

extension Step: ValidJSONData { }

extension Step: JSONCodable { }
