//
// User.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation
import RESTAPI

public struct User: Codable {

    public var _id: UUID
    /** Unique identifier of the user */
    public var name: String
    
    public init(_id: UUID, name: String) { 
        self._id = _id
        self.name = name
    }
    
    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case name
    }
}

extension User: ValidJSONData { }

extension User: JSONCodable { }

public extension User {
    
    public static var current: User?
    
    public static var all: [User] = []
    
    public static func create(user: User, _ done: @escaping (Bool) -> ()) {
        Server.shared.put("/users/\(user._id.uuidString)", data: user) { (status, _: JSON?) in
            done(status.isSuccess)
            current = user
        }
    }
    
    public static func getAll(_ done: @escaping ([User]?) -> ()) {
        Server.shared.get("/users") { (err, users: [User]?) in
            guard let users = users else { return }
            all = users
            done(users)
        }
    }
}

public extension User {
    
    func invite(_ other: User, as side: Side = .light) -> Game {
        return Game(_id: UUID(), owner: self, ownerSide: side, guest: other, steps: nil, status: .pending)
    }
}
